apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 2G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce