# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "bento/ubuntu-22.04"
    ubuntu.vm.network "private_network", ip: "192.168.56.10"
    ubuntu.vm.hostname =  "ubuntu"
    ubuntu.vm.provider "virtualbox" do |vb|
    	vb.memory = "1024"
    end
  end
end
